package CuatroEnLinea.Logica;

import CuatroEnLinea.Vista.Game;
import CuatroEnLinea.Vista.Game2;

public class TerminarGame {
	//CONSTRUCTOR DE LA CLASE
	public TerminarGame(){
		
	}
	//METODO QUE PERMITE ELIMINAR TODO REGISTRO DEL JUEGO J1 VS J2
	/**
	 * @see Se usa en los Frames de juego para finalizar cada juego
	 */
	public void Botones(){
		Game2 botones = new Game2();
		botones.setP1(false);
		botones.setP2(false);
		botones.setP3(false);
		botones.setP4(false);
		botones.setP5(false);
		botones.setP6(false);
		botones.setP7(false);
		botones.setO1(false);
		botones.setO2(false);
		botones.setO3(false);
		botones.setO4(false);
		botones.setO5(false);
		botones.setO6(false);
		botones.setO7(false);
		botones.setU1(false);
		botones.setU2(false);
		botones.setU3(false);
		botones.setU4(false);
		botones.setU5(false);
		botones.setU6(false);
		botones.setU7(false);
		botones.setY1(false);
		botones.setY2(false);
		botones.setY3(false);
		botones.setY4(false);
		botones.setY5(false);
		botones.setY6(false);
		botones.setY7(false);
		botones.setT1(false);
		botones.setT2(false);
		botones.setT3(false);
		botones.setT4(false);
		botones.setT5(false);
		botones.setT6(false);
		botones.setT7(false);
		botones.setR1(false);
		botones.setR2(false);
		botones.setR3(false);
		botones.setR4(false);
		botones.setR5(false);
		botones.setR6(false);
		botones.setR7(false);
		
		botones.setA1(null);
		botones.setA2(null);
		botones.setA3(null);
		botones.setA4(null);
		botones.setA5(null);
		botones.setA6(null);
		botones.setA7(null);
		botones.setB1(null);
		botones.setB2(null);
		botones.setB3(null);
		botones.setB4(null);
		botones.setB5(null);
		botones.setB6(null);
		botones.setB7(null);
		botones.setC1(null);
		botones.setC2(null);
		botones.setC3(null);
		botones.setC4(null);
		botones.setC5(null);
		botones.setC6(null);
		botones.setC7(null);
		botones.setD1(null);
		botones.setD2(null);
		botones.setD3(null);
		botones.setD4(null);
		botones.setD5(null);
		botones.setD6(null);
		botones.setD7(null);
		botones.setE1(null);
		botones.setE2(null);
		botones.setE3(null);
		botones.setE4(null);
		botones.setE5(null);
		botones.setE6(null);
		botones.setE7(null);
		botones.setF1(null);
		botones.setF2(null);
		botones.setF3(null);
		botones.setF4(null);
		botones.setF5(null);
		botones.setF6(null);
		botones.setF7(null);
	}
	//METODO QUE PERMITE BORRAR TODO REGISTRO DEL JUEGO J1 VS COMP
	public void Botones1(){
		Game botones = new Game();
		botones.setP1(false);
		botones.setP2(false);
		botones.setP3(false);
		botones.setP4(false);
		botones.setP5(false);
		botones.setP6(false);
		botones.setP7(false);
		botones.setO1(false);
		botones.setO2(false);
		botones.setO3(false);
		botones.setO4(false);
		botones.setO5(false);
		botones.setO6(false);
		botones.setO7(false);
		botones.setU1(false);
		botones.setU2(false);
		botones.setU3(false);
		botones.setU4(false);
		botones.setU5(false);
		botones.setU6(false);
		botones.setU7(false);
		botones.setY1(false);
		botones.setY2(false);
		botones.setY3(false);
		botones.setY4(false);
		botones.setY5(false);
		botones.setY6(false);
		botones.setY7(false);
		botones.setT1(false);
		botones.setT2(false);
		botones.setT3(false);
		botones.setT4(false);
		botones.setT5(false);
		botones.setT6(false);
		botones.setT7(false);
		botones.setR1(false);
		botones.setR2(false);
		botones.setR3(false);
		botones.setR4(false);
		botones.setR5(false);
		botones.setR6(false);
		botones.setR7(false);
		
		botones.setA1(null);
		botones.setA2(null);
		botones.setA3(null);
		botones.setA4(null);
		botones.setA5(null);
		botones.setA6(null);
		botones.setA7(null);
		botones.setB1(null);
		botones.setB2(null);
		botones.setB3(null);
		botones.setB4(null);
		botones.setB5(null);
		botones.setB6(null);
		botones.setB7(null);
		botones.setC1(null);
		botones.setC2(null);
		botones.setC3(null);
		botones.setC4(null);
		botones.setC5(null);
		botones.setC6(null);
		botones.setC7(null);
		botones.setD1(null);
		botones.setD2(null);
		botones.setD3(null);
		botones.setD4(null);
		botones.setD5(null);
		botones.setD6(null);
		botones.setD7(null);
		botones.setE1(null);
		botones.setE2(null);
		botones.setE3(null);
		botones.setE4(null);
		botones.setE5(null);
		botones.setE6(null);
		botones.setE7(null);
		botones.setF1(null);
		botones.setF2(null);
		botones.setF3(null);
		botones.setF4(null);
		botones.setF5(null);
		botones.setF6(null);
		botones.setF7(null);
	}
}
